### ISSUE TITLE
Initdecomp fails with ne1024 pg2 runs on Cori

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#323] opened 2020-07-01 17:10 UTC
@crterai reported a crash with ne1024 pg2 scream dyamond runs on Cori. The stack trace is given below for reference,
```
   32: *** Error in `/global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne1024pg2_r0125_oRRS18to6v3.FSCREAM-HR-DYAMOND1.1536x8x16.PREQX_DYCORE_REPLAY.20200623-17/bld/e3sm.exe': free(): corrupted unsorted chunks: 0x0000000025\

5e25e0 ***

   40: *** Error in `/global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne1024pg2_r0125_oRRS18to6v3.FSCREAM-HR-DYAMOND1.1536x8x16.PREQX_DYCORE_REPLAY.20200623-17/bld/e3sm.exe': free(): corrupted unsorted chunks: 0x0000000024\

bd55f0 ***

   72: GPTLstop thread 0: timer for a:PIO:pio_swapm had not been started.

  104: *** Error in `/global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne1024pg2_r0125_oRRS18to6v3.FSCREAM-HR-DYAMOND1.1536x8x16.PREQX_DYCORE_REPLAY.20200623-17/bld/e3sm.exe': free(): corrupted unsorted chunks: 0x000000001c\

dde4e0 ***

…

   32: forrtl: error (76): Abort trap signal

….

   32: Image              PC                Routine            Line        Source             

   32: e3sm.exe           0000000003848CBE  Unknown               Unknown  Unknown

   32: e3sm.exe           000000000318D440  Unknown               Unknown  Unknown

   32: e3sm.exe           000000000381C100  Unknown               Unknown  Unknown

   32: e3sm.exe           00000000039792B1  Unknown               Unknown  Unknown

   32: e3sm.exe           000000000399AA07  Unknown               Unknown  Unknown

   32: e3sm.exe           00000000039A0F33  Unknown               Unknown  Unknown

   32: e3sm.exe           00000000039A27E1  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000001FD45F7  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000001FD20F3  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000001FCA2C3  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000001F2C1AC  piolib_mod_mp_pio         597  piolib_mod.F90

   32: e3sm.exe           0000000000573EA7  cam_grid_support_        3711  cam_grid_support.F90

   32: e3sm.exe           000000000052A808  cam_history_suppo         658  cam_history_support.F90

   32: e3sm.exe           0000000000506973  cam_history_mp_h_        4137  cam_history.F90

   32: e3sm.exe           00000000004FFA39  cam_history_mp_ws        4650  cam_history.F90

   32: e3sm.exe           00000000004EFA61  cam_comp_mp_cam_r         382  cam_comp.F90

   32: e3sm.exe           00000000004DC6F3  atm_comp_mct_mp_a         563  atm_comp_mct.F90

   32: e3sm.exe           000000000042104F  component_mod_mp_         737  component_mod.F90

   32: e3sm.exe           0000000000403F9B  cime_comp_mod_mp_        2822  cime_comp_mod.F90

   32: e3sm.exe           0000000000420CB3  MAIN__                    133  cime_driver.F90

   32: e3sm.exe           0000000000401ADE  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000003971DCF  Unknown               Unknown  Unknown

   32: e3sm.exe           00000000004019CA  Unknown               Unknown  Unknown

 
```
He is working on a branch off E3SM master and his case directory is,
```
/global/cscratch1/sd/terai/E3SM_simulation/master.ne1024pg2_r0125_oRRS18to6v3.FSCREAM-HR-DYAMOND1.1536x8x16.PREQX_DYCORE_REPLAY.20200623-17
```
The run script for the case is available at 
```
/global/cfs/cdirs/e3sm/terai/run_scripts/run.ne1024pg2_scream.dyamond1.preqxDYCORE.200701.sh 
```

**Comment by jayeshkrishna** [comment] 2020-07-01 17:11
I did ask him to try setting the maximum I/O pending requests (comp2io) to 64 for testing but the problem persists.

**Comment by dqwu** [comment] 2020-07-04 02:09
@crterai 
I was not able to reproduce this issue with latest scream. I used the same script with some minor changes but got a different error (run time 00:18:37) instead. Should I use an old hash of scream?

```
ERROR:
FLDLST: Column output is specified for tape  2 but no fields defined for that tape.

Image              PC                Routine            Line        Source
e3sm.exe           000000000383DBC6  Unknown               Unknown  Unknown
e3sm.exe           0000000001CA3D5C  shr_abort_mod_mp_         114  shr_abort_mod.F90
e3sm.exe           00000000004F4FC3  cam_history_mp_fl        2354  cam_history.F90
e3sm.exe           00000000004F0B0C  cam_history_mp_in         430  cam_history.F90
e3sm.exe           00000000004F032C  cam_comp_mp_cam_i         195  cam_comp.F90
e3sm.exe           00000000004E2201  atm_comp_mct_mp_a         314  atm_comp_mct.F90
e3sm.exe           0000000000423F8F  component_mod_mp_         257  component_mod.F90
e3sm.exe           0000000000411C81  cime_comp_mod_mp_        1347  cime_comp_mod.F90
e3sm.exe           0000000000420C64  MAIN__                    122  cime_driver.F90
```

**Comment by crterai** [comment] 2020-07-09 02:03
@dqwu 
My apologies for the slow reply. I traced back your error message to something that I had set in the run_script that I had shared. I have removed the line in user_nl_cam that sets empty_htapes to true and updated the script so that it should not run into said error. Would you try running the updated script?
`/global/cfs/cdirs/e3sm/terai/run_scripts/run.ne1024pg2_scream.dyamond1.preqxDYCORE.200701.sh `

**Comment by dqwu** [comment] 2020-07-09 17:00
@crterai 
From your CaseStatus, it seems that the errors occurred about 22 mins after model execution started 
```
2020-06-29 16:12:41: model execution starting 
 ---------------------------------------------------
2020-06-29 16:34:51: model execution error 
```
With the updated script and 40-min walltime, my case run did not encounter errors before TIMEOUT.
I need to rerun it with 3:29:00 walltime like yours.
Since Cori will be down for maintenance (from July 10 to July 14), we might have to wait a few days for the run result.

**Comment by crterai** [comment] 2020-07-09 18:08
@dqwu 
Thank you for the update. Okay, do let me know what happens to the longer submission. 
The fact that it ran for 40-min without encountering errors is promising though. Do you know of any recent changes to the scream master from an I/O perspective that might have affected this?

**Comment by dqwu** [comment] 2020-07-09 18:23
> @dqwu
> Thank you for the update. Okay, do let me know what happens to the longer submission.
> The fact that it ran for 40-min without encountering errors is promising though. Do you know of any recent changes to the scream master from an I/O perspective that might have affected this?

I have no idea how recent changes to the scream master might affect the run result. Let's see whether my case run can reproduce the errors first. Below are the hashes for my case run.

```
Hash of scream master branch:
commit cffc1ce9a82e6b88ccbb800bd96e9e9abfc8762d
Date:   Wed Jul 1 16:39:12 2020 -0600
Merge Pull Request #442 from E3SM-Project/scream/test_all_int_args_fix

Hash of scorpio master branch:
commit aacd832dda560d09fe845536f2678d69db064065
Date:   Tue Jun 2 12:47:09 2020 -0500
Merge pull request #309 from E3SM-Project/jayeshkrishna/update_ver_1_1_1
```

**Comment by dqwu** [comment] 2020-07-09 23:24
@crterai @jayeshkrishna 
My latest case run (Run time 00:20:35) reproduced your memory corruption. With some debug information I added, it failed during box_rearrange_create (counter = 35, ioid = 546)

My previous case run (TIMEOUT with 40-min walltime) only reached box_rearrange_create (counter = 34, ioid = 545), maybe this slow progress is related to a known issue that sometimes it might take more time reading input files on Cori.

My debug information also confirms that the cause of this memory corruption is the same as issue #324 (to be fixed by PR #326).
I will apply PR #326 to rerun this case to see if it can be fixed as well.

**Comment by dqwu** [comment] 2020-07-14 15:16
@crterai @jayeshkrishna 
My latest case run with the fix (Run time 00:33:31) still failed. However, it might be another issue for you to take a look.
Actually, this time, the case run had reached box_rearrange_create (counter = 55, ioid = 566) before the errors occurred.

```
  461: ** WARNING IN P3_MAIN -- src, gcol, lon, lat, lvl, tstep, T:  900, 19514326, 299.4539, -63.5730,    6,       11,              NaN
  461: ** WARNING IN P3_MAIN -- src, gcol, lon, lat, lvl, tstep, Qv  900, 19514326, 299.4539, -63.5730,    6,       11,              NaN
  461: ** WARNING IN P3_MAIN -- src, gcol, lon, lat, lvl, tstep, T:  900, 19514326, 299.4539, -63.5730,    7,       11,              NaN
  461: ** WARNING IN P3_MAIN -- src, gcol, lon, lat, lvl, tstep, Qv  900, 19514326, 299.4539, -63.5730,    7,       11,              NaN
  461:  ERROR: shr_assert_in_domain: state%t has invalid value                      NaN
  461:   at location:           13           6
  461:  Expected value to be a number.
  461:  ERROR: NaN produced in physics_state by package micro_p3.
  461: Image              PC                Routine            Line        Source
  461: e3sm.exe           000000000383DFC6  Unknown               Unknown  Unknown
  461: e3sm.exe           0000000001CA3D5C  shr_abort_mod_mp_         114  shr_abort_mod.F90
  461: e3sm.exe           0000000001CB7812  shr_assert_mod_mp         325  shr_assert_mod.F90.in
  461: e3sm.exe           0000000000898AE1  physics_types_mp_         570  physics_types.F90
  461: e3sm.exe           0000000000896490  physics_types_mp_         458  physics_types.F90
  461: e3sm.exe           00000000008AF1C0  physics_update_mo         123  physics_update_mod.F90
  461: e3sm.exe           00000000008BB8D7  physpkg_mp_tphysb        2652  physpkg.F90
  461: e3sm.exe           00000000008B25B3  physpkg_mp_phys_r        1057  physpkg.F90
  461: e3sm.exe           000000000306EFD3  Unknown               Unknown  Unknown
  461: e3sm.exe           00000000030268B0  Unknown               Unknown  Unknown
  461: e3sm.exe           0000000003025B0A  Unknown               Unknown  Unknown
  461: e3sm.exe           000000000306F389  Unknown               Unknown  Unknown
  461: e3sm.exe           0000000003189599  Unknown               Unknown  Unknown
  461: e3sm.exe           00000000039E8F7F  Unknown               Unknown  Unknown
  461: Rank 461 [Tue Jul 14 03:02:10 2020] [c1-1c1s5n1] application called MPI_Abort(MPI_COMM_WORLD, 1001) - process 461
  461: forrtl: error (76): Abort trap signal
  461: Image              PC                Routine            Line        Source
  461: e3sm.exe           0000000003849EBE  Unknown               Unknown  Unknown
  461: e3sm.exe           000000000318E640  Unknown               Unknown  Unknown
  461: e3sm.exe           000000000381D300  Unknown               Unknown  Unknown
  461: e3sm.exe           000000000397A4B1  Unknown               Unknown  Unknown
  461: e3sm.exe           00000000032C2BB2  Unknown               Unknown  Unknown
  461: e3sm.exe           0000000003290BFB  Unknown               Unknown  Unknown
  461: e3sm.exe           0000000003297465  Unknown               Unknown  Unknown
  461: e3sm.exe           0000000001DCDC9A  shr_mpi_mod_mp_sh        2127  shr_mpi_mod.F90
  461: e3sm.exe           0000000001CA3E0A  shr_abort_mod_mp_          69  shr_abort_mod.F90
  461: e3sm.exe           0000000001CB7812  shr_assert_mod_mp         325  shr_assert_mod.F90.in
  461: e3sm.exe           0000000000898AE1  physics_types_mp_         570  physics_types.F90
  461: e3sm.exe           0000000000896490  physics_types_mp_         458  physics_types.F90
  461: e3sm.exe           00000000008AF1C0  physics_update_mo         123  physics_update_mod.F90
  461: e3sm.exe           00000000008BB8D7  physpkg_mp_tphysb        2652  physpkg.F90
  461: e3sm.exe           00000000008B25B3  physpkg_mp_phys_r        1057  physpkg.F90
  461: e3sm.exe           000000000306EFD3  Unknown               Unknown  Unknown
  461: e3sm.exe           00000000030268B0  Unknown               Unknown  Unknown
  461: e3sm.exe           0000000003025B0A  Unknown               Unknown  Unknown
  461: e3sm.exe           000000000306F389  Unknown               Unknown  Unknown
  461: e3sm.exe           0000000003189599  Unknown               Unknown  Unknown
  461: e3sm.exe           00000000039E8F7F  Unknown               Unknown  Unknown
srun: error: nid02581: task 461: Aborted
```

**Comment by dqwu** [comment] 2020-07-14 15:25
@crterai 
You can rerun the test with latest scorpio develop branch that contains the fix for this issue, to see if you can also reproduce the new NaN issue.
```
cd externals/scorpio
git checkout develop
```
You can try scorpio classic for comparison if possible (xmlchange PIO_VERSION=1, not sure if that will have performance issues, though).

PS, PR #326 will be merged to close this issue, since the NaN issue seems to be a different one.

**Closed** 2020-07-14 16:14 UTC
Labels: High Priority, bug

**Comment by crterai** [comment] 2020-07-14 18:22
Thanks, @dqwu! Yes, that's the crash in the model that I was hoping to diagnose with extra output, so the fix you applied seems to have worked. I will give it a try.

**Comment by dqwu** [comment] 2020-07-14 18:41
> Thanks, @dqwu! Yes, that's the crash in the model that I was hoping to diagnose with extra output, so the fix you applied seems to have worked. I will give it a try.

FYI, since that PR has been merged to scorpio, you can try latest scorpio master branch as well.
```
cd externals/scorpio
git checkout master
```
It will take some time for next release of scorpio (the default version checked out after "git submodule update --init") to be merged to E3SM repo's master branch (even longer for scream repo).

**Comment by jayeshkrishna** [comment] 2020-07-14 21:04
We are releasing a new version of Scorpio today and an E3SM PR to update the Scorpio revision in E3SM master. So in a couple of days the fix should be available in E3SM master, meanwhile you can use the Scorpio master as described by @dqwu above.

**Comment by crterai** [comment] 2020-07-14 21:46
Thanks for the clarification, @jayeshkrishna and @dwu. I've just updated my local copy of scorpio with the latest master that includes the pull request from earlier today and am submitting the simulation. I will update once it runs.
