### ISSUE TITLE
Fix E3SM integration test failures with Scorpio

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#202] opened 2019-05-16 16:20 UTC
This issue is to track fixing the Scorpio test failures in the E3SM integration test suite. We might need to create more issues based on the cause of the failures but this issue should be used to track fixing issues with the entire E3SM integration test suite.

E3SM integration tests that fail with Scorpio on Cori with E3SM master, v1.1.0-beta-2387-gea2e55628 (Scorpio test results: https://my.cdash.org/viewTest.php?onlyfailed&buildid=1716238 , Scorpio classic test results : https://my.cdash.org/viewTest.php?onlyfailed&buildid=1716798, Some tests failed with Scorpio due to CIME errors and passed on resubmission : https://my.cdash.org/viewTest.php?onlypassed&buildid=1716846):

Name | Status (Scorpio) | Time (Scorpio) | Details (Scorpio) | Summary (Scorpio) | Status with Scorpio classic | Resolution
-- | -- | -- | -- | -- | -- | --
HOMME_P24.f19_g16_rx1.A.cori-knl_intel | Failed | 1h 2m 31s | Completed (FAIL) | Broken | Failed
SMS.ne30_oECv3.BGCEXP_BCRC_CNPECACNT_1850.cori-knl_intel.clm-bgcexp | Failed | 0s | Completed (FAIL) | Broken | Failed
SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.cori-knl_intel.clm-bgcexp | Failed | 0s | Completed (FAIL) | Broken | Failed
SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6 | Failed | 11m 49s | Completed (FAIL) | Broken | Failed
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.cori-knl_intel.cam-cosplite_nhtfrq5 | Failed | 3m 51s | Completed (FAIL) | Broken | Passed
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.cori-knl_intel | Failed | 2m 19s | Completed (FAIL) | Broken | Failed
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.cori-knl_intel.cam-thetahy_pg2 | Failed | 2m 21s | Completed (FAIL) | Broken | Failed

Some E3SM integration tests pass with Scorpio but fail with Scorpio classic. These tests are listed below (E3SM master : v1.1.0-beta-2387-gea2e55628)

Name | Status (Scorpio classic) |Time (Scorpio classic) | Details (Scorpio classic) | Summary (Scorpio classic) | Status with Scorpio
-- | -- | -- | -- | -- | --
ERIO.ne30_g16_rx1.A.cori-knl_intel | Failed | 55m 25s | Completed (FAIL) | Broken | Passed
ERS.f09_g16.ICLM45BC.cori-knl_intel | Failed | 33m 10s | Completed (FAIL) | Broken | Passed

**Comment by dqwu** [comment] 2019-05-30 16:30
The following 2 tests can pass with latest E3SM master branch (use PIO1)
ERS_Ld5.T62_oQU120.CMPASO-NYF.cori-knl_intel 
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel

A new E3SM branch dqwu/test_pio2_04 has been created (based on latest E3SM master) and these 2 tests passed with it. Will rerun all integration tests on Cori with that branch to update the list of failed tests.

**Comment by jayeshkrishna** [comment] 2019-10-10 18:47
E3SM integration tests that fail with PIO2 on Cori with E3SM branch dqwu/test_pio2_03 (2019-05-17 : https://my.cdash.org/viewTest.php?onlyfailed&buildid=1651159):


Name | Status |Time | Details | Summary
-- | -- | -- | -- | --
ERS_Ld5.T62_oQU120.CMPASO-NYF.cori-knl_intel | Failed | 2m 58s | Completed (FAIL) | Broken
PEM_Ln9.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel | Failed | 8m 29s | Completed (FAIL) | Broken
PET_Ln9_PS.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel.allactive-mach-pet | Failed | 4m 55s | Completed (FAIL) | Broken
SMS.f09_g16_a.MALI.cori-knl_intel | Failed | 0s | Completed (FAIL) | Broken
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel | Failed | 1m 16s | Completed (FAIL) | Broken
SMS_B.ne4_ne4.FC5AV1C-L-AQUAP.cori-knl_intel.cam-hommexx | Failed | 0s | Completed (FAIL) | Broken
SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.cori-knl_intel.allactive-v1cmip6 | Failed | 11m 41s | Completed (FAIL) | Broken
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.cori-knl_intel.cam-cosplite_nhtfrq5 | Failed | 3m 22s | Completed (FAIL) | Broken
SMS_P12x2.ne4_oQU240.A_WCYCL1850.cori-knl_intel.allactive-mach_mods | Failed | 2m 30s | Completed (FAIL) | Broken

**Comment by dqwu** [comment] 2019-11-15 15:58
@jayeshkrishna 
For SMS_D_Ln5.ne4_ne4.FC5AV1C-L.cori-knl_intel.cam-cosplite_nhtfrq5,
I can confirm that it passed with Scorpio classic but failed with Scorpio on Cori.

It turns out to be a potential bug on E3SM side (Scorpio actually helps us to notice this issue).
I will create an issue and provide a fix for E3SM master branch.

**Comment by jayeshkrishna** [comment] 2019-11-23 01:43
See https://github.com/E3SM-Project/E3SM/pull/3318 that includes fix for issues with SMS_D_Ln5.ne4_ne4.FC5AV1C-L.cori-knl_intel.cam-cosplite_nhtfrq5

**Comment by jayeshkrishna** [comment] 2020-01-06 16:27
@dqwu: Can we close this issue now?

**Comment by dqwu** [comment] 2020-01-07 15:10
@jayeshkrishna 
I think we can close it now.
PS, we can rerun the integration test suite with latest E3SM and latest scorpio to confirm that there are no tests that would pass with scorpio classic but fail with scorpio.

**Closed** 2020-01-07 15:34 UTC
Labels: High Priority, Next Release, bug
